name: $(SourceBranchName)_$(date:yyyyMMdd)$(rev:.r)

trigger:
- master

pool:
  name: 'MOD Agents'

jobs:
- job: build_wheel
  container: 'moddevices/devtools:ub18-py36'

  steps:
  - script: |
      sudo python3 -m pip install --upgrade pip setuptools wheel twine
      sudo python3 -m pip install --upgrade keyring artifacts-keyring keyrings.alt
    displayName: 'Install dependencies'

  - task: PipAuthenticate@1
    inputs:
      artifactFeeds: 'moddevices'
    displayName: 'Pip Authenticate'

  - script: |
      # always build wheel for dev
      SETUP_BUILD_ID='$(Build.BuildId)' python3 -m pip wheel -w '$(Build.ArtifactStagingDirectory)' .

      # if commit is marked with tag 'release' then build a wheel for release
      tags=($(git tag --points-at HEAD))
      if [[ " ${tags[@]} " =~ v[0-9].* ]]; then
        python3 -m pip wheel -w '$(Build.ArtifactStagingDirectory)' .
        package_version=v$(python3 setup.py package_version)
        echo "##vso[build.addbuildtag]$package_version"
      fi
    displayName: 'Build wheels'

  - task: TwineAuthenticate@1
    inputs:
      artifactFeed: 'moddevices'
    displayName: 'Twine Authenticate'

  - script: |
      python3 -m twine upload -r moddevices --config-file $(PYPIRC_PATH) '$(Build.ArtifactStagingDirectory)/mod_lilvlib-*'
    displayName: 'Twine upload wheels'

- job: build_debian_pkg
  container: 'moddevices/devtools:ub18-py36'
  steps:
  - script: |
      sudo apt-get update -qq
      sudo apt-get install --no-install-recommends -qy libpcre3-dev devscripts pkg-config swig debhelper python3-numpy
      ./build-python3-lilv.sh
      cp ./*.deb '$(Build.ArtifactStagingDirectory)'
    displayName: 'Build debian package'

  - upload: '$(Build.ArtifactStagingDirectory)'
    artifact: 'drop'
    displayName: 'Upload Manifests'
