#!/bin/bash

PREFIX=/opt/mod
LV2DIR=/opt/mod/lib/lv2

if [ ! -d $LV2DIR/meta ]; then
  echo "$LV2DIR/meta directory is missing"
  exit
fi

if [ ! -d $LV2DIR/schemas.lv2 ]; then
  echo "$LV2DIR/schemas.lv2 directory is missing"
  exit
fi

# don't check all lv2 bundles, if atom.lv2 is installed the others should be too
if [ ! -d $LV2DIR/atom.lv2 ]; then
  echo "$LV2DIR/atom.lv2 directory is missing"
  exit
fi

if [ ! -d $LV2DIR/mod.lv2 ]; then
  echo "$LV2DIR/mod.lv2 directory is missing"
  exit
fi

if [ ! -d $LV2DIR/kx-programs.lv2 ]; then
  echo "$LV2DIR/kx-programs.lv2 directory is missing"
  exit
fi

if [ "$1"x == ""x ]; then
  echo "usage: $0 /path/to/bundle"
  exit
fi

exec $PREFIX/bin/sord_validate $(find \
  $LV2DIR/meta \
  $LV2DIR/{atom,buf-size,data-access,dynmanifest,event,instance-access,log,lv2core,midi,morph,options,parameters,patch,port-groups,port-props,presets,resize-port,schemas,state,time,ui,units,urid,uri-map,worker}.lv2 \
  $LV2DIR/mod.lv2 \
  $LV2DIR/modgui.lv2 \
  $LV2DIR/modpedal.lv2 \
  $LV2DIR/kx-meta \
  $LV2DIR/kx-external-ui.lv2 \
  $LV2DIR/kx-programs.lv2 \
  $LV2DIR/kx-rtmempool.lv2 \
  -name '*.ttl') $(find "$@" -name '*.ttl')
